//! `help`: a command's help, the whole reference in Markdown, and a skill
//! file that teaches coding agents to drive smith. The reference is walked
//! from the command tree, so it is as current as `--help`.
const std = @import("std");
const Writer = std.Io.Writer;
const cli = @import("../cli.zig");
const Ctx = @import("../Ctx.zig");

pub const command: cli.Command = .{
    .name = "help",
    .summary = "Show help for a command; `help reference` prints every command and flag as Markdown, `help skill` a SKILL.md for coding agents.",
    .usage = "[<command>... | reference | skill]",
    .max_args = 8,
    .run = run,
};

const environment = [_][2][]const u8{
    .{ "SMITH_TOKEN", "Token for the default host only (its exact name, https unless configured)" },
    .{ "SMITH_TOKEN_<HOST>", "Token for one host, e.g. SMITH_TOKEN_GIT_EXAMPLE_COM" },
    .{ "SMITH_HOST", "Default host when not in a clone" },
    .{ "SMITH_CONFIG_DIR", "Where hosts.zon and config.zon live" },
    .{ "SMITH_KEYRING", "none to keep tokens in hosts.zon, or secret-tool / security" },
    .{ "SMITH_LOGIN_TIMEOUT", "Seconds the browser login waits (default 300)" },
    .{ "SMITH_EDITOR, VISUAL, EDITOR", "Editor for bodies" },
    .{ "SMITH_BROWSER, BROWSER", "Browser for --web" },
    .{ "SMITH_PAGER, PAGER", "Pager for lists, views and diffs on a terminal (cat for none)" },
    .{ "SMITH_PROMPT_DISABLED", "Never prompt, as if `config set prompt disabled`" },
    .{ "SMITH_JQ", "The jq program --jq runs" },
    .{ "NO_COLOR, CLICOLOR_FORCE", "Colour off, colour on" },
};

const exit_codes = [_][2][]const u8{
    .{ "0", "Success" },
    .{ "1", "Failure or usage error; checks or a run failed with --exit-status" },
    .{ "2", "Cancelled at a prompt" },
    .{ "4", "Authentication failed or a login is needed" },
    .{ "8", "Checks or a run still pending, or a run waiting for approval" },
};

const conventions =
    \\- **Repository**: inside a clone smith works out the host and `owner/repo`
    \\  from the git remotes; anywhere, `-R [HOST/]OWNER/REPO` names one.
    \\  Commands without a repository take `--hostname`.
    \\- **Structured output**: commands that show API objects take `--json`
    \\  (the objects as Forgejo sent them), `-q/--jq EXPR` and
    \\  `-t/--template TEMPLATE` (Go text/template with gh's helpers). Piped,
    \\  tables are tab-separated with plain numbers, whole text, raw
    \\  timestamps and a state column.
    \\- **No prompts off a terminal**: pass what a prompt would ask for.
    \\  Creation needs `--title` and `--body` (or `--body-file -`, or
    \\  `pr create --fill`); deletion needs `--yes`; secrets and tokens are read from
    \\  standard input. `SMITH_PROMPT_DISABLED=1` makes a terminal behave the
    \\  same way.
    \\- **Messages** go to standard error; standard output carries only what a
    \\  command produces (tables, bodies, URLs, JSON).
    \\- **Anything else**: `smith api <endpoint>` calls Forgejo's REST API with
    \\  the stored login (`-X`, `-f`, `-F`, `--paginate`).
    \\
;

fn run(ctx: *Ctx, args: *const cli.Args) !u8 {
    const root = &@import("../app.zig").root;
    const words = args.positionals;
    if (words.len == 1 and std.mem.eql(u8, words[0], "reference")) {
        try reference(ctx.out, root);
        return 0;
    }
    if (words.len == 1 and std.mem.eql(u8, words[0], "skill")) {
        try skill(ctx.out);
        return 0;
    }
    const r = try cli.resolve(ctx.alloc, root, words);
    if (r.rest.len > 0) return ctx.fail("unknown command \"{s}\"; see `smith help`", .{r.rest[0]});
    try cli.writeHelp(ctx.out, r.path);
    return 0;
}

fn reference(w: *Writer, root: *const cli.Command) !void {
    try w.print("# smith {s} reference\n\n{s}\n\nGenerated by `smith help reference`.\n\n## Conventions\n\n{s}\n## Exit codes\n\n| Code | Meaning |\n|---|---|\n", .{ @import("../app.zig").version, root.summary, conventions });
    for (exit_codes) |e| try w.print("| {s} | {s} |\n", .{ e[0], e[1] });
    try w.writeAll("\n## Environment\n\n| Variable | Effect |\n|---|---|\n");
    for (environment) |e| try w.print("| `{s}` | {s} |\n", .{ e[0], e[1] });
    try w.writeAll("\n## Commands\n");
    var buffer: [8]*const cli.Command = undefined;
    var path: std.ArrayList(*const cli.Command) = .initBuffer(&buffer);
    for (root.subs) |*sub| try commandSection(w, root, sub, &path);
}

fn commandSection(w: *Writer, root: *const cli.Command, cmd: *const cli.Command, path: *std.ArrayList(*const cli.Command)) !void {
    path.appendAssumeCapacity(cmd);
    defer _ = path.pop();
    try w.print("\n{s} {s}", .{ if (path.items.len == 1) "###" else "####", root.name });
    for (path.items) |c| try w.print(" {s}", .{c.name});
    try w.print("\n\n{s}\n", .{cmd.summary});
    if (cmd.subs.len > 0) {
        for (cmd.subs) |*sub| try commandSection(w, root, sub, path);
        return;
    }
    try w.print("\n```\n{s}", .{root.name});
    for (path.items) |c| try w.print(" {s}", .{c.name});
    if (cmd.usage.len > 0) try w.print(" {s}", .{cmd.usage});
    try w.writeAll(" [flags]\n```\n");
    const implicit = cli.implicitFlags(cmd);
    if (cmd.flags.len + implicit.len == 0) return;
    try w.writeByte('\n');
    for ([_][]const cli.Flag{ cmd.flags, implicit }) |group| for (group) |f| {
        try w.writeAll("- `");
        if (f.short) |s| try w.print("-{c}, ", .{s});
        try w.print("--{s}", .{f.long});
        if (f.value) |v| try w.print(" {s}", .{v});
        try w.print("`: {s}\n", .{f.help});
    };
}

fn skill(w: *Writer) !void {
    try w.print(
        \\---
        \\name: smith
        \\description: Work with Forgejo (and Gitea) from the shell with smith, a gh-compatible CLI - pull requests, issues, Actions runs, releases, repositories, labels, milestones, secrets, the REST API. Use when a task touches a Forgejo or Gitea forge, or a repository whose remote is one.
        \\---
        \\
        \\# smith
        \\
        \\smith is `gh` for Forgejo: the same command names and flags wherever
        \\Forgejo can back them (`smith pr create`, `smith run watch`,
        \\`smith issue list --label bug`). Written for smith {s}.
        \\
        \\Before using a command you have not used in this session, read its
        \\help (`smith <command> --help`), or everything at once with
        \\`smith help reference`. Do not guess flags from gh: some differ, and
        \\several gh commands do not exist because Forgejo has no API for them.
        \\
        \\## Rules for agents
        \\
        \\{s}- **Exit codes**: 1 failure, 2 cancelled, 4 authentication needed
        \\  (tell the user to run `smith auth login --hostname HOST`; never ask for
        \\  their password or token), 8 pending.
        \\- **Check the login** with `smith auth status` before writing.
        \\- **Confirm destructive actions with the user** before passing `--yes`
        \\  (repo delete, release delete, label delete...).
        \\
        \\## Common tasks
        \\
        \\```sh
        \\smith pr list --json -q '.[] | [.number, .title] | @tsv'
        \\smith pr create --title "Fix login" --body-file - <<'EOF'
        \\...
        \\EOF
        \\smith pr checks 12 --watch        # exit 1 failed, 8 still pending
        \\smith pr view 12 --comments
        \\smith issue create --title "Crash on start" --body "Steps: ..."
        \\smith run list -L 5 && smith run view <id> --log-failed
        \\smith release create v1.2.0 dist/* --notes-file CHANGELOG-excerpt.md
        \\smith api /repos/{{owner}}/{{repo}}/branches --jq '.[].name'
        \\```
        \\
    , .{ @import("../app.zig").version, conventions });
}
